[workflow]
workflow_schedule_interval = "@daily"
sequential_queue = "sequential"
default_queue = "general"

[db]
db_identifier = "andrew-rds-instance"
db_connection = "andrew-rds-postgres"
username = 'postgres'
password = 'Clashallday1!'
host = 'andrew-rds-instance.cvwhaidrmrqj.us-east-2.rds.amazonaws.com'
port = '5432'  # Default port for PostgreSQL
default_db = 'postgres'  # Default database you can connect to
db_name = 'lab8db'
db_alchemy_driver = "postgresql+psycopg2"

[files]
s3_bucket = "andrewawsbucket"
s3_file_key = "heart_disease.csv"
remote_file = "heart_disease.csv"
local_file = "heart_disease.csv"

[sklearn]
train_test_ratio = 0.1
labels = "target"

[spark]
number_of_folds = 5
split_seed = 7576
train_test_split = 0.9
labels = "target"
